### ISSUE TITLE
Example of Instruction-Tuning Training

### ISSUE THREAD

**Issue by BowieHsu** [tatsu-lab/stanford_alpaca#10]
Hello, thank you for open-sourcing this work. We are now interested in generating our own instructions to fine-tune the Llama model based on your documentation and approach. Could you please advise on any resources or references we can use? Also, are these codes available on Hugging Face?

**Comment by Tiiiger** [comment]
Hi @BowieHsu 

this repo contains the relevant code for generating instructions and check the README for how to run that

**Comment by BowieHsu** [comment]
@Tiiiger Hi, thank you for your response.  
Your documentation is excellent, and I now understand the instruction generation approach. 
Now I want to reproduce the training task and I found this repository, https://github.com/nebuly-ai/nebullvm, which seems to have a similar instruction fine-tuning training approach as yours. Is it consistent with your training method, and are there any codes that can be referenced there?

**Comment by Tiiiger** [comment]
hi @BowieHsu unfortunately we have no knowledge of this repo and cannot be more helpful.

**Comment by rtaori** [comment]
Hi,

Quick update - We have released the training code, see https://github.com/tatsu-lab/stanford_alpaca#fine-tuning. Hope this is helpful.

**Comment by BowieHsu** [comment]
@rtaori Thank you, my friend. I'll have all my GPUs running at full power to express my gratitude.
