### ISSUE TITLE
We are thinking about why this small model can store enough world knowledge

### ISSUE THREAD

**Issue by RedBlack888** [tatsu-lab/stanford_alpaca#11]
Hi, we find your work in home page.
https://crfm.stanford.edu/2023/03/13/alpaca.html
This work inspires us how to adjust large language models in a good way.
Now, We are thinking about why this small model can store enough world knowledge. 

Best.

**Comment by lxuechen** [comment]
Hi, thanks for your interest! We're glad our work has brought value to the community and your research. Looking forward to seeing more research coming out!
