### ISSUE TITLE
Newest PyTorch version not working

### ISSUE THREAD

**Issue by suciokhan** [tatsu-lab/stanford_alpaca#117]
Hello, I installed from your requirements.txt on a fresh version of python3.10, but when I attempt training I get the following error:

`ValueError: Your setup doesn't support bf16/gpu. You need torch>=1.10, using Ampere GPU with cuda>=11.0`

However, I indeed have a version higher than that. The requirements.txt file installed `2.0.0+cu117`, which I verified by calling `torch.__version__` inside of python3.10.

Can you please share the specific version of torch you used so I can install that one? Thank you.

**Comment by luzai** [comment]
May I ask which PyTorch version you are using? Thank you~

**Comment by suciokhan** [comment]
'2.0.0+cu117'
