### ISSUE TITLE
Are there any particular reason for using `### ` for instruction, input and response?

### ISSUE THREAD

**Issue by timothylimyl** [tatsu-lab/stanford_alpaca#165]
I know that in markdown format `### ` is treated as section/subsection title. Are there any relevance there?

Edit to make the question clearer:
In the training script, the inputs are formulated as such:
```
PROMPT_DICT = {
    "prompt_input": (
        "Below is an instruction that describes a task, paired with an input that provides further context. "
        "Write a response that appropriately completes the request.\n\n"
        "### Instruction:\n{instruction}\n\n### Input:\n{input}\n\n### Response:"
    ),
    "prompt_no_input": (
        "Below is an instruction that describes a task. "
        "Write a response that appropriately completes the request.\n\n"
        "### Instruction:\n{instruction}\n\n### Response:"
    ),
}
```

My question is why do we need to put the `### `?  Is llama trained specifically to detect this token as something special?

**Comment by adithyab94** [comment]
ChatGPT which is used to create this dataset uses Markdown format for its response. `###` represents heading 3 style

**Comment by timothylimyl** [comment]
@adithyab94  any reference document to this?

I am curious now on what are the other special tokens?

**Comment by michieal** [comment]
Well, I do know that LLaMa was trained in much the same way. If you have it generate a random prompt, more often than not, you get the training code, `### Instruction`, `### Input` and `### Response` rather than just a normal output from say, something like ChatGPT.
