### ISSUE TITLE
Why resize embedding?

### ISSUE THREAD

**Issue by nrailgun** [tatsu-lab/stanford_alpaca#175]
https://github.com/tatsu-lab/stanford_alpaca/blob/main/train.py#L75-L95

The token embedding vocab of llama release by FB is 32000, but I found the vocab size is changed to 32001, and the last embedding is initialized by averaging trained embeddings. Isn't that random noise?

**Comment by llwx593** [comment]
> https://github.com/tatsu-lab/stanford_alpaca/blob/main/train.py#L75-L95
> 
> The token embedding vocab of llama release by FB is 32000, but I found the vocab size is changed to 32001, and the last embedding is initialized by averaging trained embeddings. Isn't that random noise?

Hi, when I use weight_diff.py to recover weight, this phenomenon is also found, resulting in the inability to merge. May I ask if there is any solution?

**Comment by Yclock** [comment]
> > https://github.com/tatsu-lab/stanford_alpaca/blob/main/train.py#L75-L95
> > The token embedding vocab of llama release by FB is 32000, but I found the vocab size is changed to 32001, and the last embedding is initialized by averaging trained embeddings. Isn't that random noise?
> 
> Hi, when I use weight_diff.py to recover weight, this phenomenon is also found, resulting in the inability to merge. May I ask if there is any solution?



> > https://github.com/tatsu-lab/stanford_alpaca/blob/main/train.py#L75-L95
> > The token embedding vocab of llama release by FB is 32000, but I found the vocab size is changed to 32001, and the last embedding is initialized by averaging trained embeddings. Isn't that random noise?
> 
> Hi, when I use weight_diff.py to recover weight, this phenomenon is also found, resulting in the inability to merge. May I ask if there is any solution?



> > https://github.com/tatsu-lab/stanford_alpaca/blob/main/train.py#L75-L95
> > The token embedding vocab of llama release by FB is 32000, but I found the vocab size is changed to 32001, and the last embedding is initialized by averaging trained embeddings. Isn't that random noise?
> 
> Hi, when I use weight_diff.py to recover weight, this phenomenon is also found, resulting in the inability to merge. May I ask if there is any solution?

Hi, have you sloved this error?
