### ISSUE TITLE
web demo agree button does nothing.

### ISSUE THREAD

**Issue by tljstewart** [tatsu-lab/stanford_alpaca#2]

**Comment by winsomehax** [comment]
> 

It does eventually, but it's very slow. Popularity has its downsides!

**Comment by tjbck** [comment]
@Tiiiger have you guys deployed the quantised version of the model on the web demo? if it hasn't been, quantising the model might help with speeding up the inference process.

**Comment by lxuechen** [comment]
Hi folks, we have improved our system's throughput. The site is back up and running much faster than before. Thanks for the patience!
