### ISSUE TITLE
[Q] How much vRAM does finetuning LLaMa 7B require?

### ISSUE THREAD

**Issue by NightMachinery** [tatsu-lab/stanford_alpaca#21]
How much vRAM does finetuning LLaMa 7B require?

What was the hardware used to train Alpaca?

**Comment by c-goosen** [comment]
Read the release: https://crfm.stanford.edu/2023/03/13/alpaca.html

**Comment by c-goosen** [comment]
"Fine-tuning a 7B LLaMA model took 3 hours on 8 80GB A100s, which costs less than $100 on most cloud compute providers."
