### ISSUE TITLE
train llama-7b with single A100-80G GPU, out of memory error 

### ISSUE THREAD

**Issue by gzm2062** [tatsu-lab/stanford_alpaca#220]
I use a single A100-80G GPU to train fine tune llama-7b and get OOM error every time.
however, when manually load model, it turns out that the model only takes 20G/80G, which makes this OOM error very strange for me.

**here is the error msg**
n136-082-206:15496:15968 [0] NCCL INFO comm 0x555b51b3e2d0 rank 0 nranks 1 cudaDev 0 busId c9000 - Init COMPLETE
  0%|                                                                                                                                                                                    | 0/30033 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/opt/tiger/codealpaca/train.py", line 225, in <module>
    train()
  File "/opt/tiger/codealpaca/train.py", line 219, in train
    trainer.train()
  File "/usr/local/lib/python3.10/site-packages/transformers/trainer.py", line 1639, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.10/site-packages/transformers/trainer.py", line 1904, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/usr/local/lib/python3.10/site-packages/transformers/trainer.py", line 2662, in training_step
    self.scaler.scale(loss).backward()
  File "/usr/local/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 86.00 MiB (GPU 0; 79.35 GiB total capacity; 74.58 GiB already allocated; 42.19 MiB free; 77.99 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
  0%|                                                                                                                                                                                    | 0/30033 [00:01<?, ?it/s]
n136-082-206:15496:15973 [0] NCCL INFO [Service thread] Connection closed by localRank 0
n136-082-206:15496:15496 [0] NCCL INFO comm 0x555b51b3e2d0 rank 0 nranks 1 cudaDev 0 busId c9000 - Abort COMPLETE
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 15496) of binary: /usr/local/bin/python3.10
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/usr/local/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-04-16_20:21:21
  host      : n136-082-206.byted.org
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 15496)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
./run.sh: line 16: --save_total_limit: command not found

**run.sh**
torchrun --nproc_per_node=1 --master_port=9004 train.py \
    --model_name_or_path "/mnt/bn/moemodel/llama-7b-hf" \
    --data_path "./data/code_alpaca_20k.json" \
    --fp16 True \
    --output_dir "/mnt/bn/moemodel/llama-7b-hf-gg" \
    --num_train_epochs 3 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 500 \
    --logging_strategy steps \
    --logging_steps 50 \
    --logging_dir "/mnt/bn/moemodel/tensorboard"
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --deepspeed ds_config.json \
    --tf32 False

**ds_config.json**
{
    "zero_optimization": {
        "stage": 3,
        "contiguous_gradients": true,
        "stage3_max_live_parameters": 0,
        "stage3_max_reuse_distance": 0,
        "stage3_prefetch_bucket_size": 0,
        "stage3_param_persistence_threshold": 100,
        "reduce_bucket_size": 100,
        "sub_group_size": 100000000,
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": true
        },
        "offload_param": {
            "device": "cpu",
            "pin_memory": true
        },
        "stage3_gather_16bit_weights_on_model_save": true
    },
    "optimizer": {
        "type": "Adam",
        "params": {
            "lr": 0.00002,
            "betas": [
                0.9,
                0.999
            ],
            "eps": 1e-8,
            "weight_decay": 0
        }
    },
    "fp16": {
        "enabled": true,
        "auto_cast": false,
        "loss_scale": 0,
        "initial_scale_power": 32,
        "loss_scale_window": 1000,
        "hysteresis": 2,
        "min_loss_scale": 1
    },
    "train_batch_size": "auto",
    "steps_per_print": 10,
    "train_micro_batch_size_per_gpu": "auto",
    "wall_clock_breakdown": false
}

**Comment by Minxiangliu** [comment]
Hi @gzm2062 ,
Can you share the solution to the issue? I am facing the same error as you.
