### ISSUE TITLE
Exception: Could not find the transformer layer class to wrap in the model

### ISSUE THREAD

**Issue by s33kh** [tatsu-lab/stanford_alpaca#224]
It is the same issue as with [issue#58](https://github.com/tatsu-lab/stanford_alpaca/issues/58)

I am using transformer version 4.28.1 and using the following argument

--fsdp_transformer_layer_cls_to_wrap "LLaMADecoderLayer"

**Comment by lxuechen** [comment]
They changed the class name in a later commit. You'd need to use `LlamaDecoderLayer `.
