### ISSUE TITLE
fine-tuning a 7B model requires about 7 x 4 x 4 = 112 GB of VRAM? how to understand the formula?

### ISSUE THREAD

**Issue by dragen1860** [tatsu-lab/stanford_alpaca#241]
Dear all:
  I can not understand the VRAM formula. as for me, each parameters use 4 bytes size, so 7B model requires about 7 * 4 = 28GB VRAM. why the formula say 7*4*4? thank you.

**Comment by Coldmooon** [comment]
I think the last 4 means 4 GPUs on one machine, since the original sentence says "Naively ..." which potentially does not enable "FSDP ".  Correct me if I'm wrong.

**Comment by zhsu-private** [comment]
Read the ZeRo paper and you will understand

**Comment by lxuechen** [comment]
the formula is a memory lower bound for when things are in fp32. if you use adam, you'd need to store 2 running averages (first and second moment). to train, you'd also need to store the gradient. then ofc, there's one copy of the parameter. this results in 4 "copies" of the model. 

ofc, memory reduction can be achieved by casting some of these tensors to fp16 or bf16.
