### ISSUE TITLE
Public release of model weights

### ISSUE THREAD

**Issue by topiconcept** [tatsu-lab/stanford_alpaca#25]
Congratulations on the fine-tune! We have observed some fantastic performance through the provided web interface.

AFAIK the original Llama model was released under GNU/GPL, you should be able to distribute derivative work respecting this original license, correct? (Even if the original model weights have not officially been distributed to the public yet)

Will you provide some sort of wait-list to notify us when the model weights are made available?

Interested in as much information as you may share on this, again, congratulations and thank your impressive work!

https://github.com/facebookresearch/llama/blob/main/LICENSE

**Comment by rtaori** [comment]
We are double checking with our lawyers about this. We will let you know about any updates.

**Comment by topiconcept** [comment]
Thank you very much for your efforts @rtaori, we are really eager to access the model, you guys have done an impressive work!
