### ISSUE TITLE
Question on License : commercial use permitted, but at the same time, research-purpose only ?

### ISSUE THREAD

**Issue by tetsu-kikuchi** [tatsu-lab/stanford_alpaca#262]
The [LICENSE](https://github.com/tatsu-lab/stanford_alpaca/blob/main/LICENSE) of this repo is Apache 2.0 and it is written that commercial use is permitted.

On the other hand, In README.md, it is said that "Alpaca is intended and licensed for research use only."

These two information seem contradicting.  Could anyone tell me what I am misunderstanding?  Thank you.

**Comment by gregor-soniox** [comment]
You can do whatever you want with the code but the model weights and the training set are only for academic use.

**Comment by yutohub** [comment]
@gregor-soniox What is the license for seed_tasks.jsonl?
