### ISSUE TITLE
could be open source the model ?

### ISSUE THREAD

**Issue by ucas010** [tatsu-lab/stanford_alpaca#27]
hi ,dear
the model could be open source ?

**Comment by samchen8008** [comment]
I dont think so. it depends on Meta's LLaMa 7B which is also not opensource. probably it will be opensource in the future.

**Comment by LRLVEC** [comment]
> 

LLaMA is open source, you can download the weights everywhere.

**Comment by windprak** [comment]
We need a hf converted LLaMA version. Would this one work? https://huggingface.co/decapoda-research/llama-7b-hf

**Comment by rtaori** [comment]
Hi,

Not an update about Alpaca weights, but we have released the training code, see https://github.com/tatsu-lab/stanford_alpaca#fine-tuning. This should allow you to train your own model if you have access to LLAMA. Please open a new issue for any further questions/concerns.
