### ISSUE TITLE
Older Mac

### ISSUE THREAD

**Issue by betolley** [tatsu-lab/stanford_alpaca#272]
My main computer is a older iMac 27 inch.  It has 16 gb ram and a Quadro 4 GB video card.  The video card only support cuda 3.  Is it possible to retrain using CPU only?

**Comment by gugongerguo** [comment]
Experience summary: 7B model training requires 200G*80% memory

**Comment by betolley** [comment]
Thanks.  Guess I will wait until 2032 to do it :) .  I did use fxmarty/tiny-llama-fast-tokenizer to play around and was able to train a LORA with it with my own json.  So at least I am doing it right.
