### ISSUE TITLE
Not quite understand the importance of this repo.

### ISSUE THREAD

**Issue by 19245222** [tatsu-lab/stanford_alpaca#31]
Hi, devs at stanford. Today I took a try on your project and run the command to generate the data. And after awhile, it outputs a json file, regen.json like below. So I have a little confused, forgive my ignorance but I really don't know how to make something cool with this "regex.json" file. You know what I mean, is like I got a file, but what can I do with it. I guessed ppl might able to create something similar to ChatGpt but weaker, this is my guessing so far. Please enlightened me, thanks.
![image](https://user-images.githubusercontent.com/110375103/225282349-d5929adc-1bd5-44eb-86f7-af0edfe4421a.png)

**Comment by rtaori** [comment]
Hi,

Thanks for your interest. We have just released training code, see https://github.com/tatsu-lab/stanford_alpaca#fine-tuning. This should give you the ability to train your own models similar to Alpaca.
