### ISSUE TITLE
why 52K?

### ISSUE THREAD

**Issue by i-am-neo** [tatsu-lab/stanford_alpaca#37]
Hello, thank you for open-sourcing your training details!  I just tried your demo and found the responses surprisingly fluent.

Wondering if your decision to train on a 52K instruction dataset was influenced by some criteria?  I'm wondering if there's a floor where you found responses to be qualitatively inferior, or trying a number beyond 52K to have not yielded better results?

**Comment by rtaori** [comment]
Hi,
We were running low on credits and so decided to stop at 52K. We haven't tried, by my bet is that with more data, the model could be made even better.
