### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by waterhorse1** [tatsu-lab/stanford_alpaca#39]
Hi

Great work! In READM, you guys mention that 4 A100 80G can train this model, but when I try 8 40G A100, it meets cuda oom error.

**Comment by charliezjw** [comment]
Did you try reduce the batch size?

**Comment by KurtFeynmanGodel** [comment]
Had the same problem. Batch sizes of 2 and grad accumulation of 1 fixed it . But ETA ~= 8hrs.

**Comment by waterhorse1** [comment]
> Did you try reduce the batch size?

Thank you for your reply! Yes I realize I have 8 GPUs so I should set per_device_train_batch_size to 2 right? If that's right then I do make it work

**Comment by KurtFeynmanGodel** [comment]
How do I make the code use all 8 GPUs? From the monitoring data, it seems like it is using only 4 out of 8. I am not familiar with the whole fdsp sharding stuff. A hint in the right direction on what to tweak would be nice thanks. I tried using accelerate to craft a custom device_map but that did not work.  

Thanks in advance.

![image](https://user-images.githubusercontent.com/99613321/225518830-73872646-da4b-49cb-ba21-f0e23833e795.png)

**Comment by KurtFeynmanGodel** [comment]
Also I seem to be getting a lot of intermittent fsdp memory errors.  Started happening at about 51% then 62% and 72% (Every 10% ?). I am hoping that the code isn't skipping over training data and the final result would still be close to yours. Any idea why this is happening, how I can fix it and if it would cause quality issues?


`{'loss': 0.5737, 'learning_rate': 1.0073901570302426e-05, 'epoch': 1.54}                                                                                                     
 51%|████████████████████████████████████████████████████████████████▌                                                             | 10000/19503 [4:10:30<4:00:59,  1.52s/it]/home/ubuntu/.local/lib/python3.10/site-packages/torch/distributed/fsdp/_state_dict_utils.py:312: UserWarning: Failed to clone() tensor with name _fsdp_wrapped_module.model.layers.21.mlp.up_proj.weight on rank 1. This may mean that this state_dict entry could point to invalid memory regions after returning from state_dict() call if this parameter is managed by FSDP. Please check clone implementation of _fsdp_wrapped_module.model.layers.21.mlp.up_proj.weight. Error: CUDA out of memory. Tried to allocate 172.00 MiB (GPU 1; 39.45 GiB total capacity; 37.08 GiB already allocated; 138.25 MiB free; 37.44 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`


![image](https://user-images.githubusercontent.com/99613321/225579188-7259d600-adff-4a54-9322-65f7bbfa1c62.png)

**Comment by KurtFeynmanGodel** [comment]
Why do you have an evaluate function in the trainer? Is that necessary?

**Comment by waterhorse1** [comment]
> Why do you have an evaluate function in the trainer? Is that necessary?

just comment it.

**Comment by KurtFeynmanGodel** [comment]
I did that but only after the application crashed. Now I am trying to resume from checkpoint but I cannot resume from checkpoint. Do I need to do anything special to resume from a fsdp checkpoint? I currently just load the checkpoint model and call train("checkpoint-18000") but the checkpoint model refuses to load with the errors below. Any idea  how to properly load an fsdp checkpoint? Thanks.


`Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 415, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_utils.py", line 169, in _rebuild_tensor_v2
    tensor = _rebuild_tensor(storage, storage_offset, size, stride)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_utils.py", line 148, in _rebuild_tensor
    return t.set_(storage._untyped_storage, storage_offset, size, stride)
RuntimeError: Trying to resize storage that is not resizable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 419, in load_state_dict
    if f.read(7) == "version":
  File "/usr/local/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 128: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/alpaca/stanford_alpaca/train.py", line 245, in <module>
    train()
  File "/home/ubuntu/alpaca/stanford_alpaca/train.py", line 207, in train
    model = transformers.AutoModelForCausalLM.from_pretrained(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2630, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2939, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 431, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for 'output/checkpoint-18000/pytorch_model-00002-of-00003.bin' at 'output/checkpoint-18000/pytorch_model-00002-of-00003.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.`

**Comment by edfall** [comment]
> > > Why do you have an evaluate function in the trainer? Is that necessary?
> > 
> > 
> > just comment it.
> 
> I did that but only after the application crashed. Now I am trying to resume from checkpoint but I cannot resume from checkpoint. Do I need to do anything special to resume from a fsdp checkpoint? I currently just load the checkpoint model and call train("checkpoint-18000") but the checkpoint model refuses to load with the errors below. Any idea how to properly load an fsdp checkpoint? Would appreciate any insights you might have. Thanks.
> 
> `
> 
> **EDIT: I was loading the checkpoint with the wrong path above. But I believe when i fix that I get another error. like so. Traceback (most recent call last): File "/home/ubuntu/alpaca/stanford_alpaca/train.py", line 246, in train() File "/home/ubuntu/alpaca/stanford_alpaca/train.py", line 239, in train trainer.train("output/checkpoint-18000/") File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/trainer.py", line 1617, in train self._load_from_checkpoint(resume_from_checkpoint) File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/trainer.py", line 2120, in _load_from_checkpoint load_result = load_sharded_checkpoint(model, resume_from_checkpoint, strict=is_sagemaker_mp_enabled()) File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 385, in load_sharded_checkpoint state_dict = torch.load(os.path.join(folder, shard_file), map_location="cpu") File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/serialization.py", line 809, in load return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args) File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/serialization.py", line 1172, in _load result = unpickler.load() File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_utils.py", line 169, in _rebuild_tensor_v2 tensor = _rebuild_tensor(storage, storage_offset, size, stride) File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_utils.py", line 148, in _rebuild_tensor return t.set_(storage._untyped_storage, storage_offset, size, stride) RuntimeError: Trying to resize storage that is not resizable WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 122406 closing signal SIGTERM WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 122407 closing signal SIGTERM WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 122409 closing signal SIGTERM ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 2 (pid: 122408) of binary: /usr/local/bin/python3.10 Traceback (most recent call last): File "/home/ubuntu/.local/bin/torchrun", line 8, in sys.exit(main()) File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/**init**.py", line 346, in wrapper return f(*args, **kwargs) File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main run(args) File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run elastic_launch( File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in **call** return launch_agent(self._config, self._entrypoint, list(args)) File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent raise ChildFailedError( torch.distributed.elastic.multiprocessing.errors.ChildFailedError: **`

Have you solved this problem? I have faced the same issue
