### ISSUE TITLE
Training code detail.

### ISSUE THREAD

**Issue by bhanuc** [tatsu-lab/stanford_alpaca#4]
Thanks for sharing this project. I have been trying to train the larger model for an offline first free education assistant for poor students preparing for competitive exams  . Sharing training code, even if in an pr can really helpful for me fine-tune an education assistant.

**Comment by lxuechen** [comment]
Hi,

Thanks for your interest! We will release the training code in the coming weeks. We're particularly waiting for LLAMA support in huggingface to become stable.

**Comment by YannDubs** [comment]
@bhanuc see https://github.com/tatsu-lab/stanford_alpaca/tree/main#fine-tuning
