### ISSUE TITLE
Loading llama-7b from huggingface 

### ISSUE THREAD

**Issue by puyuanliu** [tatsu-lab/stanford_alpaca#43]
Could you share the link to the adopted llama-7b model? I was trying the one from decapoda-research (https://huggingface.co/decapoda-research) (https://huggingface.co/decapoda-research/llama-7b-hf/discussions) but it looks like the model itself cannot be loaded.

**Comment by charliezjw** [comment]
I think you can try the weight conversion part of this PR: https://github.com/huggingface/transformers/pull/21955

**Comment by puyuanliu** [comment]
Thanks a lot! Will try!

**Comment by AgaMiko** [comment]
@charliezjw  Works great for me, thanks!

**Comment by puyuanliu** [comment]
@charliezjw That works for me too, thanks!
