### ISSUE TITLE
OpenAIError Error communicating with OpenAI

### ISSUE THREAD

**Issue by 19245222** [tatsu-lab/stanford_alpaca#44]
Hello, I kept receive this issue. 
![image](https://user-images.githubusercontent.com/110375103/225495268-20b9fe29-aea9-42ec-a324-072e2662adc0.png)

**Comment by Tiiiger** [comment]
Hi look like this is a problem with your open ai setup. 

Please check the openai repo for this.

**Comment by 19245222** [comment]
> 

So I checkout the https://github.com/openai/openai-quickstart-python.git repo to try using OpenAi server and "text-Davinci-03". And the result is surprisingly good. Look at the pic below. You can see, I can receive a response from OpenAI successfully, it fails only when I use your repo.
![image](https://user-images.githubusercontent.com/110375103/225530374-642646fe-7db0-4677-949e-4f5afeab7e9c.png)
