### ISSUE TITLE
OOM issue

### ISSUE THREAD

**Issue by puyuanliu** [tatsu-lab/stanford_alpaca#46]
Can this finetuning script fit into A10, which only has 24GB GPU memory? I am trying to fine-tune the model on 4 A10 GPUs using a batch size of 1, but I still get an OOM error.

**Comment by puyuanliu** [comment]
Just tried using 8 A100 (40GB), still having OOM issue after one iteration:

{'loss': 1.6692, 'learning_rate': 1.360544217687075e-07, 'epoch': 0.0}                                                                                                                                                                                                                                                      
  0%|                                                                                                                                                                                                                                                                                  | 1/4875 [00:06<7:54:55,  5.85s/it]Traceback (most recent call last):
  File "stanford_alpaca/train.py", line 235, in <module>
Traceback (most recent call last):
  File "stanford_alpaca/train.py", line 235, in <module>
    train()
  File "stanford_alpaca/train.py", line 228, in train
    trainer.train()
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/transformers/trainer.py", line 1633, in train
    return inner_training_loop(
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/transformers/trainer.py", line 1900, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/transformers/trainer.py", line 2662, in training_step
    loss.backward()
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 388.00 MiB (GPU 2; 39.59 GiB total capacity; 36.74 GiB already allocated; 120.19 MiB free; 37.37 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.

**Comment by kriskrisliu** [comment]
4x A100-80GB is ok, and gpu memory is almost fully allocated...

**Comment by leondelee** [comment]
can i train using only 1 A100-80G?

**Comment by leondelee** [comment]
> 4x A100-80GB is ok, and gpu memory is almost fully allocated...

can i train using only 1 A100-80G?

**Comment by puyuanliu** [comment]
8 * A100 (40GB) worked after using fp16 instead of bp16

**Comment by KurtFeynmanGodel** [comment]
With the same configuration and fp16 I could do batch size of 2 but with gradient accumulation of 1. Did you use gradient accumulation of 8 with bp16?

**Comment by puyuanliu** [comment]
Yes I was using grad accumulation of 8 with batch size 1.

KurtFeynmanGodel ***@***.***> 于 2023年3月16日周四 08:21写道：

**Comment by puyuanliu** [comment]
No, I haven't tried to resume training from the checkpoint. Mine is roughly 6 hours. But I got OOM error after the last epoch.

**Comment by yysjasmine** [comment]
> No, I haven't tried to resume training from the checkpoint. Mine is roughly 6 hours. But I got OOM error after the last epoch.

Could you please share your python version and pytorch version? I run in 4 * A100 (40GB) with batch_size=1, fp16=True and gradient_accumulation_steps=1, but I still got OOM in the first epoch. I suspect that there's something wrong with my envirenment. Thanks a lot.

**Comment by puyuanliu** [comment]
@yysjasmine Try this command. 
torchrun --nproc_per_node=8 --master_port=1234 train.py --model_name_or_path converted_llama_7B --data_path ./alpaca_data.json --fp16 True --output_dir ./trained_model --num_train_epochs 1  --per_device_train_batch_size 1  --per_device_eval_batch_size 1 --gradient_accumulation_steps 8 --evaluation_strategy "no" --save_strategy "steps" --save_steps 2000 --save_total_limit 1 --learning_rate 2e-5 --weight_decay 0. --warmup_ratio 0.03 --lr_scheduler_type "cosine" --logging_steps 1 --fsdp "full_shard auto_wrap" --fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer'

**Comment by jtang613** [comment]
LLaMA-13B (HF) Fails with OOM on a dual A100-80GB.
`torchrun --nproc_per_node=2 --master_port=9999 train.py     --model_name_or_path ../llama-13b/     --data_path ./alpaca_data.json     --fp16 True     --output_dir ../alpaca-13b/     --num_train_epochs 3     --per_device_train_batch_size 1     --per_device_eval_batch_size 1     --gradient_accumulation_steps 8     --evaluation_strategy "no"     --save_strategy "steps"     --save_steps 2000     --save_total_limit 1     --learning_rate 2e-5     --weight_decay 0.     --warmup_ratio 0.03     --lr_scheduler_type "cosine"     --logging_steps 1     --fsdp "full_shard auto_wrap"     --fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer`

(also tested with nproc=1, also fails with OOM)

`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 606.00 MiB (GPU 1; 79.18 GiB total capacity; 77.07 GiB already allocated; 468.31 MiB free; 77.41 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Mem
ory Management and PYTORCH_CUDA_ALLOC_CONF`

**Comment by yysjasmine** [comment]
> @yysjasmine Try this command. torchrun --nproc_per_node=8 --master_port=1234 train.py --model_name_or_path converted_llama_7B --data_path ./alpaca_data.json --fp16 True --output_dir ./trained_model --num_train_epochs 1 --per_device_train_batch_size 1 --per_device_eval_batch_size 1 --gradient_accumulation_steps 8 --evaluation_strategy "no" --save_strategy "steps" --save_steps 2000 --save_total_limit 1 --learning_rate 2e-5 --weight_decay 0. --warmup_ratio 0.03 --lr_scheduler_type "cosine" --logging_steps 1 --fsdp "full_shard auto_wrap" --fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer'

Thank you, I will try the command.

**Comment by Ahtesham00** [comment]
@yysjasmine did the command work with 4 A100 ?
