### ISSUE TITLE
does support multi-turn training data?

### ISSUE THREAD

**Issue by trouble-maker007** [tatsu-lab/stanford_alpaca#49]
Thanks for the greate job to help us easy to finetune on llama
I found that the training data is just single turn, does support for the mulit-turn data like [OIG](https://huggingface.co/datasets/laion/OIG)

**Comment by YannDubs** [comment]
Neither the training nor the generations pipeline currently support multi-turn! But that’s an interesting question to look into!!

**Comment by trouble-maker007** [comment]
@YannDubs Thanks for  the response

**Comment by MrRace** [comment]
> Neither the training nor the generations pipeline currently support multi-turn! But that’s an interesting question to look into!!

How to use stanford_alpaca do multi-turn chat? How to write the inference code? Could you share an example？ Thanks a lot!
