### ISSUE TITLE
Support for gpt-3.5-turbo

### ISSUE THREAD

**Issue by iamnafets** [tatsu-lab/stanford_alpaca#5]
`gpt-3.5-turbo` is cheaper and faster than davinci. I'm not 100% sure whether it will actually work better for Alpaca but figure it may be worth a trial. Any interest in taking a PR?

**Comment by kaneda2004** [comment]
Should only cost approx $60 to generate the dataset using the turbo model. Can you imagine fine tuning the LLM for a total of $160 compute included. Go hard 😀

**Comment by Tiiiger** [comment]
hi @iamnafets we have no official plan to support this in this repo. 

Encourage yall to try! I have tried very briefly. It should work.
