### ISSUE TITLE
Confusion about input ids

### ISSUE THREAD

**Issue by fuxuliu** [tatsu-lab/stanford_alpaca#53]
Hi, thanks for sharing such a great job.
I've read your fine-tuning code and I'm a little confused about the inputs of the model.
From the code, the Input of model should be, here's an, example: ### # Instruction: {instruction}### Input{input}### Response:{response}. so the input_ids: tokenizer(example), label_ids:tokenizer(example), and label_ids[:len(source_len)]=IGNORE_INDEX.
I would like to ask, why do input ids contain response token ids? So the data target won't leak?

I am looking forward to your reply. Thank you very much.

**Comment by KurtFeynmanGodel** [comment]
I think that is how text completion/generation in transformers is trained for. The entire concatenated text of instruction and response.
