### ISSUE TITLE
Exception: Could not find the transformer layer class to wrap in the model

### ISSUE THREAD

**Issue by Cloopen-ReLiNK** [tatsu-lab/stanford_alpaca#58]
the version of transformers is https://github.com/huggingface/transformers/pull/21955/commits

**Comment by AgaMiko** [comment]
Try changing `fsdp_transformer_layer_cls_to_wrap` to `LlamaDecoderLayer`

**Comment by lxuechen** [comment]
See https://github.com/tatsu-lab/stanford_alpaca#warning

**Comment by Cloopen-ReLiNK** [comment]
solved

**Comment by raihan0824** [comment]
> Try changing `fsdp_transformer_layer_cls_to_wrap` to `LlamaDecoderLayer`

what about bloom model? what's the `fsdp_transformer_layer_cls_to_wrap` ?

**Comment by joshuafc** [comment]
> > Try changing `fsdp_transformer_layer_cls_to_wrap` to `LlamaDecoderLayer`
> 
> what about bloom model? what's the `fsdp_transformer_layer_cls_to_wrap` ?

do you solved the problem of fsdp_transformer_layer_cls_to_wrap  for bloom model?

**Comment by Hepta-Col** [comment]
> 

I am also using Bloom models. Did you solve it?

**Comment by huayicong23** [comment]
hello,I encountered the same problem with MOSS,how can I set fsdp_transformer_layer_cls_to_wrap?

**Comment by huayicong23** [comment]
> > Try changing `fsdp_transformer_layer_cls_to_wrap` to `LlamaDecoderLayer`
> 
> what about bloom model? what's the `fsdp_transformer_layer_cls_to_wrap` ?

you can set it to BloomBlock

**Comment by huayicong23** [comment]
> > > Try changing `fsdp_transformer_layer_cls_to_wrap` to `LlamaDecoderLayer`
> > 
> > 
> > what about bloom model? what's the `fsdp_transformer_layer_cls_to_wrap` ?
> 
> do you solved the problem of fsdp_transformer_layer_cls_to_wrap for bloom model?
you can set it to BloomBlock
