### ISSUE TITLE
'type' object is not subscriptable

### ISSUE THREAD

**Issue by knightmarehs** [tatsu-lab/stanford_alpaca#6]
The exception can be fixed by replacing 'dict' to 'Dict'

`
from typing import Optional, Sequence, Union
...
def openai_completion(
    prompts: Union[str, Sequence[str], Sequence[dict[str, str]], dict[str, str]],`
-->
`
from typing import Optional, Sequence, Union, Dict
...
def openai_completion(
    prompts: Union[str, Sequence[str], Sequence[Dict[str, str]], Dict[str, str]],`

**Comment by lxuechen** [comment]
Hi, 

Thanks for your interest! Sorry, we weren't super clear about the python version. But we're using Python 3.10 as the default in our experiments. 

Python 3.9 introduced typing with the builtin types, e.g., see [this](https://yukinarit.github.io/pyserde/guide/features/python3.9-type-hinting.html)

We'll clarify this further when we release the code for training, and make sure we have a `setup.py` or equivalent config file then.
