### ISSUE TITLE
What are the requirements for the model

### ISSUE THREAD

**Issue by moh21amed** [tatsu-lab/stanford_alpaca#66]
I just saw that you will release the fine-tuned model in the future after meta agreement 
I am just asking will I be able to run it on my laptop with 8gb ram and medium GPU or will it need more power ?

**Comment by joaopandolfi** [comment]
Can i run with llama.cpp, using CPU?

**Comment by bartman081523** [comment]
the requirements are likely the same as Llama-7B
https://github.com/oobabooga/text-generation-webui/wiki/LLaMA-model
"4-bit mode
In 4-bit mode, the LLaMA models are loaded with just 25% of their regular VRAM usage. So LLaMA-7B fits into a 6GB GPU, and LLaMA-30B fits into a 24GB GPU."

**Comment by moh21amed** [comment]
@bartman081523 thanks
