### ISSUE TITLE
Strange inference output

### ISSUE THREAD

**Issue by puyuanOT** [tatsu-lab/stanford_alpaca#70]
After training the model, the inference output isn't human-readable. 

![image](https://user-images.githubusercontent.com/121119211/225760700-25837d96-0d94-4ea0-b190-36a6a9fa79f2.png)

Any one have the same issue? How did you guys fix it?

**Comment by Xuan-ZW** [comment]
I have the same issue

**Comment by deepcs233** [comment]
same issue

**Comment by xieexiaotuzi** [comment]
same issue

**Comment by garcesmarc** [comment]
mismo problema
