### ISSUE TITLE
Questions about installing Transformer, and the versions of each environment

### ISSUE THREAD

**Issue by 447428054** [tatsu-lab/stanford_alpaca#75]
Is the following installation method correct?

pip install git+https://github.com/zphang/transformers.git@llama_push

Each version is as follows：
numpy==1.24.2
rouge-score==0.1.2
fire==0.5.0
openai==0.27.2
sentencepiece==0.1.97
wandb==0.14.0

**Comment by sallywang147** [comment]
Following - i have similar question too.

**Comment by 447428054** [comment]
> Following - i have similar question too.

I solved the problem, the code is as follows:

https://github.com/447428054/stanford_alpaca_llama.git

**Comment by Ahtesham00** [comment]
> pip install git+https://github.com/zphang/transformers.git@llama_push
> 
> Each version is as follows： numpy==1.24.2 rouge-score==0.1.2 fire==0.5.0 openai==0.27.2 sentencepiece==0.1.97 wandb==0.14.0

Have you used this for your environment?
