### ISSUE TITLE
OOM when running fine-tune in 4 A100

### ISSUE THREAD

**Issue by Hins** [tatsu-lab/stanford_alpaca#76]
Have set train/val batch_size into 1, gc.collect(), torch.cuda.empty_cache() and set PYTORCH_CUDA_ALLOC_CONF less than allocated size, still encountered "torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 388.00 MiB (GPU 2; 23.70 GiB total capacity; 21.91 GiB already allocated; 315.69 MiB free; 22.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF".
Any solution for this issue?

**Comment by puyuanliu** [comment]
A100 should have 40GB memory, are you using A10?

**Comment by Hins** [comment]
> A100 should have 40GB memory, are you using A10?

Sorry, it is A10
