### ISSUE TITLE
Dose anyone have prediction code?

### ISSUE THREAD

**Issue by Hins** [tatsu-lab/stanford_alpaca#90]

**Comment by gaopengpjlab** [comment]
Please try our simple perdition code with llama adapter:
https://github.com/ZrrSkywalker/LLaMA-Adapter

**Comment by Hins** [comment]
> Please try our simple perdition code with llama adapter: https://github.com/ZrrSkywalker/LLaMA-Adapter

@gaopengpjlab thanks for your reply, I fine-tuned llama by train.py file which used transformers' transformers.AutoModelForCausalLM.from_pretrained() and transformers.AutoTokenizer.from_pretrained() to load model and tokenizer, however in LLaMA-Adapter you showed the model is generated by pytorch, do you know how to convert transformers' fine-tuned model in LLaMA.generate()?

Thanks in advance.
